In [7]:
import tensorflow as tf

In [8]:
X=tf.Variable([[1,2,3],[4,5,6]])
Y=tf.Variable([[7,8],[9,10],[11,12]])

In [9]:
tf.print(X)

[[1 2 3]
 [4 5 6]]


In [10]:
tf.print(Y)

[[7 8]
 [9 10]
 [11 12]]


In [14]:
c1 = tf.matmul(X, Y)

In [15]:
tf.print(c1)

[[58 64]
 [139 154]]


In [16]:
c2 = tf.matmul(Y, X)
tf.print(c2)

[[39 54 69]
 [49 68 87]
 [59 82 105]]
