In [1]:
import tensorflow as tf

In [2]:
A=tf.Variable([[1,2,3,4], \
               [5,6,7,8], \
               [9,10,11,12], \
               [13,14,15,16], \
               [17,18,19,20]])
tf.print(A)

[[1 2 3 4]
 [5 6 7 8]
 [9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [7]:
A.shape

TensorShape([5, 4])

In [8]:
tf.print(tf.reshape(A, [5, 4, 1]))

[[[1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]]

 [[9]
  [10]
  [11]
  [12]]

 [[13]
  [14]
  [15]
  [16]]

 [[17]
  [18]
  [19]
  [20]]]


In [10]:
A = tf.reshape(A, [5, 4, 1])
A

<tf.Tensor: shape=(5, 4, 1), dtype=int32, numpy=
array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]],

       [[13],
        [14],
        [15],
        [16]],

       [[17],
        [18],
        [19],
        [20]]])>