In [1]:
import tensorflow as tf

In [2]:
X=tf.Variable([[91,12,15], [11,88,21],[90, 87,75]])

In [3]:
tf.print(X)

[[91 12 15]
 [11 88 21]
 [90 87 75]]


In [4]:
X.shape

TensorShape([3, 3])

In [5]:
tf.print(tf.argmax(X, axis=0))

[0 1 2]


In [ ]:
td