In [1]:
import tensorflow as tf

In [2]:
A = tf.Variable([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

In [3]:
B = tf.Variable([[1, 0, -1], [1, 0, -1], [1, 0, -1]])
B

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[ 1,  0, -1],
       [ 1,  0, -1],
       [ 1,  0, -1]])>

In [4]:
# element-wise multiplication on A and B
mult_out = tf.math.multiply(A, B)
mult_out

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 1,  0, -3],
       [ 4,  0, -6],
       [ 7,  0, -9]])>

In [5]:
# element-wise sum on mult_out
conv_out = tf.math.reduce_sum(mult_out)
conv_out

<tf.Tensor: shape=(), dtype=int32, numpy=-6>